### ISSUE TITLE
 Issue Regarding Benchmark Results Accuracy Of Medusa

### ISSUE THREAD

**Issue by wxd000000** [huggingface/text-generation-inference#1363]
### System Info

v1.3.3

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [x] My own modifications

### Reproduction

I hope this message finds you well. I am writing to bring to your attention a potential bug I encountered while working with TGI v1.3.3. Specifically, I noticed some discrepancies in the benchmark results that seem to be indicative of a bug.

when I run the benchmark of medusa based on vicuna-7b, the result looks wrong:
(tokens/secs) | Batch Size | medusa | vicuna | medusa | vicuna
-- | -- | -- | -- | -- | --
Decode | 1 | 80.51 | 89.71 | 79.24 | 88.16
  | 2 | 156.50 | 178.40 | 153.56 | 174.80
  | 4 | 291.84 | 348.89 | 282.71 | 339.99
  | 8 | 518.82 | 659.90 | 492.36 | 632.43
  | 16 | 805.12 | 1199.34 | 739.26 | 1112.74
  | 32 | 1015.27 | 2042.94 | 910.53 | 1841.44

When batch_size=1, medusa should output tokens faster than the original model. Are there errors in the statistics on the number of tokens? 

### Expected behavior

Can you show me your results and fix the bug? Thank you for taking the time to consider this matter. I am looking forward to your response and am happy to provide any further information that might be helpful.

**Comment by jiangix-paper** [comment]
Hello, I want to know how to test medusa in tgi？Such as vicuna-33b-v1.3. I have the two folders as follows:
<img width="1204" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/62198809/cd0848f0-8783-4fee-8d79-9f91d0287346">
<img width="1184" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/62198809/8291e357-740b-4402-989e-8e84fac23c07">
Should I convert the ".pt" medusa model in safetensors?

**Comment by spongezz** [comment]
I think it's not reasonable to use the text-generation-benchmark since the speed depends on the prompt. I have tested the single batch inference speed and the results looks good, 1.6x speed up on my 13B codellama. However, when I benchmark the throughput via sending asynchronous requests, the throughput becomes lower.
