### ISSUE TITLE
Madlad400 support

### ISSUE THREAD

**Issue by irshadbhat** [huggingface/text-generation-inference#1416]
### Model description

T5 based model for Machine translation.

### Open source status

- [x] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://huggingface.co/jbochi/madlad400-3b-mt#training-details

### System Info
text-generation-inference 1.3.0
python 3.10

### Information
 - [X] Docker

### Tasks
 - [X] An officially supported command

### Reproduction
The model loaded proporly but I am getting incorrect results. I want to know if the tgi 1.3.0 supports Madlad400? Thanks a lot.

### Expected behavior
Madlad400 support

**Comment by Narsil** [comment]
Is flan-t5 working correctly for you ?  https://huggingface.co/google/flan-t5-base.

We have integration-tests for t5, therefore this model should work, but we have no idea how this particular checkpoint was created, it's very possible that the model was wrongly converted: https://github.com/huggingface/text-generation-inference/blob/main/integration-tests/models/test_t5_sharded.py

**Comment by irshadbhat** [comment]
Have tested flan-t5-xl and its working fine. The results are exactly as expected.

**Comment by jhargraveiii** [comment]
We are seeing exactly the same thing with madlad400. It seems to work but produces very poor results compared to running the same model with standard transformers code. Perhaps its the pipeline type? We use "**_translation_**". flan-t5 doesn't AFAICT.

**Comment by jhargraveiii** [comment]
Can we repopen this issue? We've tested on the latest 3.0.1

**Comment by josh-at-straker** [comment]
Hey team - Jumping on this as a 'me-too'. 

We have issue on MadLad (all the google released versions on HF) and our fine-tuned variants. I'm looking for other similar t5 translation models to test with, but a new translations pipeline in TGI would be a game changer. 

The model loaded correctly, however I am getting incorrect results back from the model.
