### ISSUE TITLE
HF inference endpoint deployment does not work with recent commits

### ISSUE THREAD

**Issue by MoritzLaurer** [huggingface/text-generation-inference#1732]
### System Info

HF dedicated inference endpoints and latest version of `huggingface_hub` to create endpoints. 

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [X] My own modifications

### Reproduction

I've tested different SHAs and different models: 
SHAs that do not work: sha-eef2912  sha-cb802a2
SHAs/versions that do work: sha-4ee0a0c, 1.3.3, 1.4.5

```
from huggingface_hub import create_inference_endpoint

# define TGI as custom image
custom_image = {
    "health_route": "/health",  # Health route for TGI
    "env": {
        "MAX_BATCH_PREFILL_TOKENS": "2048", # can be adjusted to your needs
        "MAX_INPUT_LENGTH": "1024", # can be adjusted to your needs
        "MAX_TOTAL_TOKENS": "1512", # can be adjusted to your needs
        "MODEL_ID": "/repository",  # IE will save the model in /repository
    },
    "url": "ghcr.io/huggingface/text-generation-inference:sha-cb802a2", 
}

endpoint_name = "mistral-7b-instruct-v0-1-003",   #"llava-v1-6-mistral-7b-hf-002"
namespace = "MoritzLaurer"

endpoint = create_inference_endpoint(
    name=endpoint_name,
    repository="mistralai/Mistral-7B-Instruct-v0.1",  #"llava-hf/llava-v1.6-mistral-7b-hf", 
    namespace=namespace,
    framework="pytorch",
    task="text-generation",  
    accelerator="gpu",
    vendor="aws",
    region="us-east-1",
    type="protected",
    min_replica=0,
    max_replica=1,
    instance_type="p4de", 
    instance_size="xlarge",  # xlarge
    custom_image=custom_image,
)

endpoint.wait()
print(endpoint.status)
```

The result is a failed endpoint with the following error logs with different models:

error logs with mistral-7b-instruct-v0-1
```
2024/04/12 10:39:22 ~ {"timestamp":"2024-04-12T08:39:22.037042Z","level":"INFO","message":"Args { model_id: \"/rep****ory\", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: false, hf_api_token: None, hostname: \"r-moritzlaurer-mistral-7b-instruct-v0-1-000-h2sr3qar-bda80-chq1\", port: 80, uds_path: \"/tmp/text-embeddings-inference-server\", huggingface_hub_cache: Some(\"/data\"), payload_limit: 2000000, api_key: None, json_output: true, otlp_endpoint: None, cors_allow_origin: None }","target":"text_embeddings_router","filename":"router/src/main.rs","line_number":140}
2024/04/12 10:39:22 ~ Error: The `--pooling` arg is not set and we could not find a pooling configuration (`1_Pooling/config.json`) for this model.
- 2024-04-12T08:39:22.037+00:00
2024/04/12 10:39:22 ~ Caused by:
2024/04/12 10:39:22 ~ No such file or directory (os error 2)
```
error logs with llava-v1-6-mistral-7b-hf
```
2024/04/12 10:23:48 ~ {"timestamp":"2024-04-12T08:23:48.307933Z","level":"INFO","message":"Args { model_id: \"/rep****ory\", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: false, hf_api_token: None, hostname: \"r-moritzlaurer-llava-v1-6-mistral-7b-hf-001-5yf65wor-eb57c-etbi\", port: 80, uds_path: \"/tmp/text-embeddings-inference-server\", huggingface_hub_cache: Some(\"/data\"), payload_limit: 2000000, api_key: None, json_output: true, otlp_endpoint: None, cors_allow_origin: None }","target":"text_embeddings_router","filename":"router/src/main.rs","line_number":140}
2024/04/12 10:23:48 ~ Error: Failed to parse `config.json`
- 2024-04-12T08:23:48.308+00:00
2024/04/12 10:23:48 ~ Caused by:
2024/04/12 10:23:48 ~ missing field `max_position_embeddings` at line 63 column 1
```
error logs with idefics-9b-instruct
```
2024/04/12 10:22:16 ~ {"timestamp":"2024-04-12T08:22:16.027619Z","level":"INFO","message":"Args { model_id: \"/rep****ory\", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: false, hf_api_token: None, hostname: \"r-moritzlaurer-idefics-9b-instruct-002-01p01jyj-1d653-ijf3e\", port: 80, uds_path: \"/tmp/text-embeddings-inference-server\", huggingface_hub_cache: Some(\"/data\"), payload_limit: 2000000, api_key: None, json_output: true, otlp_endpoint: None, cors_allow_origin: None }","target":"text_embeddings_router","filename":"router/src/main.rs","line_number":140}
2024/04/12 10:22:16 ~ Error: The `--pooling` arg is not set and we could not find a pooling configuration (`1_Pooling/config.json`) for this model.
- 2024-04-12T08:22:16.028+00:00
2024/04/12 10:22:16 ~ Caused by:
2024/04/12 10:22:16 ~ No such file or directory (os error 2)
```

### Expected behavior

Successfully deployed endpoints with working models

**Comment by OlivierDehaene** [comment]
These are TEI errors, not TGIs. Are you sure you didn't make a mistake on the docker image?

**Comment by OlivierDehaene** [comment]
`"target":"text_embeddings_router"`

**Comment by MoritzLaurer** [comment]
Ah that was probably it, thanks!
