### ISSUE TITLE
SSE text generation not working in aws sagemaker

### ISSUE THREAD

**Issue by orellavie1212** [huggingface/text-generation-inference#786]
### System Info

I am using v0.9.4 in aws sagemaker, the endpoint is up and working great with model.deploy (HF model) in sagemaker, but I need the SSE Stream service to make the llm valuable (waiting 20+ secs even with 4 gpus is expensive).
Any idea how to invoke the /generate-stream? the /invocations of sagemaker is somewhat avoiding that.
Tried even to use the client service (pip install text-generation)

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [X] My own modifications

### Reproduction

Deploy the endpoint in sagemaker with 0.9.4 tag. (pushed to ecr the 0.9.4 as in sagemaker it was 0.8.2)

### Expected behavior

SSE should work and provide tokens as a stream.

**Comment by philschmid** [comment]
SageMaker is currently not supporting SSE events.

**Comment by orellavie1212** [comment]
thanks for the help, as I anticipated
