### ISSUE TITLE
Could not import Flash Attention enabled models: No module named 'vllm_cache_ops'

### ISSUE THREAD

**Issue by phucdoitoan** [huggingface/text-generation-inference#804]
### System Info

Full command: CUDA_VISIBLE_DEVICES=0,1 text-generation-launcher --model-id meta-llama/Llama-2-7b-chat-hf --port 8080 --trust-remote-code --env --num-shard 2
OS: Ubuntu 20
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 0e8b47811e711b46fe80e6b*****4186f83744d6
Docker label: N/A
nvidia-smi:
Thu Aug 10 07:46:13 2023       
   +-----------------------------------------------------------------------------+
   | NVIDIA-SMI 515.57       Driver Version: 515.57       CUDA Version: 11.7     |
   |-------------------------------+----------------------+----------------------+
   | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                               |                      |               MIG M. |
   |===============================+======================+======================|
   |   0  NVIDIA A100-SXM...  Off  | 00000000:01:00.0 Off |                    0 |
   | N/A   29C    P0    58W / 400W |  36526MiB / 40960MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
   |   1  NVIDIA A100-SXM...  Off  | 00000000:41:00.0 Off |                    0 |
   | N/A   29C    P0    55W / 400W |      3MiB / 40960MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
   |   2  NVIDIA A100-SXM...  Off  | 00000000:81:00.0 Off |                    0 |
   | N/A   26C    P0    52W / 400W |      3MiB / 40960MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
   |   3  NVIDIA A100-SXM...  Off  | 00000000:C1:00.0 Off |                    0 |
   | N/A   25C    P0    53W / 400W |      3MiB / 40960MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
                                                                                  
   +-----------------------------------------------------------------------------+
   | Processes:                                                                  |
   |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
   |        ID   ID                                                   Usage      |
   |=============================================================================|
   +-----------------------------------------------------------------------------+
The current version: latest v1.0 (install locally from text-generation-inference github

### Information

- [ ] Docker
- [X] The CLI directly text-generation-launcher --model-id meta-llama/Llama-2-7b-chat-hf --port 8080 --trust-remote-code --env

### Tasks

- [ ] An officially supported command
- [x] My own modifications

### Reproduction

Install locally according to the instruction in README.md, then run

CUDA_VISIBLE_DEVICES=0,1 text-generation-launcher --model-id meta-llama/Llama-2-7b-chat-hf --port 8080 --trust-remote-code --env --num-shard 2

### Expected behavior

Expect the llama models to shard and run correctly as it does when sharding on all 4 GPUs with the following command:
'text-generation-launcher --model-id meta-llama/Llama-2-7b-chat-hf --port 8080 --trust-remote-code --env'

**Comment by phucdoitoan** [comment]
It was just due to incorrect installation from source. Some how the "BUILD_EXTENSIONS=True make install" command did not excecute all the installation. Fixed the issues by manually install vllm, flash attention according to Makefile in server/Makefile

**Comment by phucdoitoan** [comment]
It was just due to incorrect installation from source. Some how the "BUILD_EXTENSIONS=True make install" command did not excecute all the installation. Fixed the issues by manually install vllm, flash attention according to Makefile in server/Makefile

**Comment by chris-aeviator** [comment]
anyone just wanting to run a model and not neccesarily requiring FlashAttention, you can bypass this issue by using --quantize bitsandbytes , you will still see the warning but the model will load. I'm aware that this is not the intention of the HF devs, since they are going to gradualy deprecate this, but I find more than often people struggle to get things running at all, before running compute optimal.

**Comment by Narsil** [comment]
This has nothing to do with bitsandbytes. We're not going to deprecate bitsandbytes.

**Comment by chris-aeviator** [comment]
my bad - I thought bitsandbytes would def. route to CausalLm by default
